### PR TITLE
Seven new die with icons on the D20s

### PR DESCRIPTION
**Pull request by over2take**
Added several new dice: 
Monk
Sun
Raven
Tome
Flower
GreatAxe
Anchor

All die have custom textures, are great for a number of class types and players. We made these in connection to characters in our current campaign and would love to contribute more in the future! 

Any suggestions are appreciated!

### CODE REVIEW

**Comment by tobloef** [comment]
Hey there, thanks a lot for making this PR. These dice a really cool and I have just a couple of points of feedback:

- A little while back I figured out that 128px by 128px is a better size for the textures, to save space without losing too much detail. I haven't updated any templates to match this, so it's pretty easy to miss. If you end up re-exporting some, or all, of the textures, please change it to that size. If not, I can also dig up a script that I have for resizing all the textures automatically.
- The numbers on the Raven D6 are maybe a bit too big. The size seems to be better on the other dice.
- The Monk dice are a bit hard to read since the contrast is low. Not sure what to do about this, if anything at all really, but it's something to perhaps consider. It may be because Roll20 shines a bright white light on the dice, which makes them look a bit different when rolled, compared to the original texture.
- I really like Tome and would consider using it for my own character, it's just a shame that the colors don't quite match the thumbnail (they yellow/orange is a bit too bright), because of the issue described above.

Some of these are pretty minor and I know it probably takes a while to re-export everything, but if you feel up for it, I think these would be some great tweaks to make.

I have also created [another PR](https://github.com/tobloef/roll20-fancy-dice/tree/pr/8-fixes) here with a few housekeeping changes to your PR, but I will hold off on merging that until this PR is final.

Once again, thanks for this PR, it's just what I had hoped someone would do when I made the extension!

**Comment by over2take** [comment]
Thank you for the review and the time to make this app!

I have pushed up changed to the branch that include: 

- Newly updated texture for the Monk dice set
- Updated text on the Raven D6
- All textures updated to 128px

I will have to revisit the Tome texture in the future. The issue right now is the Roll20 lighting on the dice is extreme causing the texture to be overexposed and washed out. 

Darker colours seem to bo a lot better and I will keep that in mind when looking at a new texture pattern for the Tome dice. 

Please let me know if there is anything I missed or can update for you! :)

**Comment by tobloef** [comment]
Look great! I will prepare it for merging and let you know once it's submitted to the chrome store.

**Comment by tobloef** [comment]
It's been submitted and should be live some time before 2021 🥳

**Pull request merged**
