### PR TITLE
Regal dice

### PR DESCRIPTION
**Pull request by Immedicale**
I added a new set of dice

### CODE REVIEW

**Comment by tobloef** [comment]
Hey there, thanks a lot for the PR! I tested it out and it looks pretty good. There are a few issues with textures not quite reaching the edges of the model, but this should be somewhat easy to fix. The readability on the numbers are also a little low, I think it's because the contrast is kinda low.

image

That being said, this is definitely a high-quality PR and I appreciate it a lot. Maybe we can work on improving the points mentioned above? I'm also curious, how did you create the textures? Thanks!

**Comment by Immedicale** [comment]
hey! I made them in gimp, by directly editing .png files. I could probably
slightly fix them, but i had trouble eyeballing the right dimensions of the
faces.

sob., 24 paź 2020, 20:30 użytkownik Tobias Løfgren <notifications@github.com>
napisał:

**Comment by tobloef** [comment]
I see, nice. I think the size fix could be fixed by resizing the textures ever so slightly.

**Comment by Immedicale** [comment]
I'll look into it tomorrow!

sob., 24 paź 2020, 20:46 użytkownik Tobias Løfgren <notifications@github.com>
napisał:

**Comment by tobloef** [comment]
Good call making the bare texture lighter, to better support custom colors 👍 They are still not the easiest to read dice, but unless you have some idea to improve that (change font maybe?), I think it's alright. I also wonder if the thumbnail would better showcase the dice if they had a color instead of being white? You call.

Oh, and a tip if you want perfect edges on your thumbnail image: If you make a Roll20 map with the background `#eeeeee` (see screenshot), you don't have to make the background transparent, as it will match the background of the button the thumbnail is on. I know it's not the most flexible of solutions, but that's how I've made the rest of the thumbnails and I don't plan on changing the background color any time soon.

Other than that, I feel like this is pretty close to being ready for a merge, so thanks a bunch!

image

**Comment by Immedicale** [comment]
Since changing the font would require remaking the textures from scratch, I
don't think that's the best option. And I think the thumbnail is "good
enough" as is.

**Comment by tobloef** [comment]
Yeah, I thought that might be the case. Sure, let me merge it then 👍

**Review by tobloef — CHANGES_REQUESTED** [review]
Oh sorry, I just noticed one final thing. Could you not submit the changes to the `package.lock` file? I would rather keep those kinds of changes independent from a new dice texture.

**Comment by Immedicale** [comment]
Sure, just tell me how should I do that? I mean, I didn't edit that file...

niedz., 25 paź 2020, 20:12 użytkownik Tobias Løfgren <
notifications@github.com> napisał:

**Comment by tobloef** [comment]
I'll just do it for you 👍

**Review by tobloef — APPROVED** [review]

**Comment by tobloef** [comment]
I have submitted a new version of the extension (that includes your dice) to the Chrome store. It should be available ~~within a day or two~~ right now!

**Comment by Immedicale** [comment]
It's already live! Thanks a bunch and keep up the good work!

niedz., 25 paź 2020, 20:39 użytkownik Tobias Løfgren <
notifications@github.com> napisał:

**Pull request merged**
